
'''
# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tyelhx9WKFs5OfvvQMKa6FQ7h3aJ_yhY
"""

# prompt: Por meio de código, crie um arquivo **dados.csv**
# contendo:
# Nome, Idade
# Ana,25
# Bruno,30
# Carla,22
# Daniel,28
# Eduardo,35

import csv

data = [
    ['Nome', 'Idade'],
    ['Ana', 25],
    ['Bruno', 30],
    ['Carla', 22],
    ['Daniel', 28],
    ['Eduardo', 35]
]

with open('dados.csv', 'w', newline='') as csvfile:
  writer = csv.writer(csvfile)
  writer.writerows(data)

# prompt: Ler o arquivo **dados.csv** e armazene os dados em uma
# lista.
# Peça ao usuário para digitar um nome.
# Verifique se o nome digitado está na lista, exiba a idade
# correspondente e se é a pessoa mais velha ou não da lista.
# Caso o nome não esteja na lista, exiba uma mensagem
# informando isso.

import csv

def process_data():
    try:
        with open('dados.csv', 'r', newline='') as csvfile:
            reader = csv.reader(csvfile)
            next(reader)  # Skip the header row
            data = list(reader)
    except FileNotFoundError:
        print("O arquivo 'dados.csv' não foi encontrado.")
        return

    names = [row[0] for row in data]
    ages = [int(row[1]) for row in data]

    user_name = input("Digite um nome: ")

    if user_name in names:
        index = names.index(user_name)
        age = ages[index]
        print(f"Idade de {user_name}: {age}")

        max_age = max(ages)
        if age == max_age:
            print(f"{user_name} é a pessoa mais velha da lista.")
        else:
            print(f"{user_name} não é a pessoa mais velha da lista.")
    else:
        print(f"O nome '{user_name}' não foi encontrado na lista.")


process_data()

# prompt: faça tratamento de erro, independente se for digitado o nome com letra maiuscula ou minuscula

'''

import csv

data = [
    ['Nome', 'Idade'],
    ['Ana', 25],
    ['Bruno', 30],
    ['Carla', 22],
    ['Daniel', 28],
    ['Eduardo', 35]
]

with open('dados.csv', 'w', newline='') as csvfile:
  writer = csv.writer(csvfile)
  writer.writerows(data)


def process_data():
    try:
        with open('dados.csv', 'r', newline='') as csvfile:
            reader = csv.reader(csvfile)
            next(reader)  # Skip the header row
            data = list(reader)
    except FileNotFoundError:
        print("O arquivo 'dados.csv' não foi encontrado.")
        return

    names = [row[0].lower() for row in data]  # Convert names to lowercase
    ages = [int(row[1]) for row in data]

    user_name = input("Digite um nome: ").lower()  # Convert input to lowercase

    if user_name in names:
        index = names.index(user_name)
        original_name = data[index][0] # Get the original name (case-sensitive)
        age = ages[index]
        print(f"Idade de {original_name}: {age}")

        max_age = max(ages)
        if age == max_age:
            print(f"{original_name} tem {age} anos, é a pessoa mais velha da lista.")
        else:
            print(f"{original_name} tem {age} anos, não é a pessoa mais velha da lista.")
    else:
        print(f"O nome '{user_name}' Nome não encontrado.")


process_data()